Add Microgateway performance test scripts
chrishantha/performance-apim pull request #7
Opened 2019-01-18 08:29 UTC by tharikaGitHub

## Purpose
This PR adds performance test components for API Microgateway.

2019-01-18 09:37 UTC, chrishantha requested changes

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/pom.xml
> +    <groupId>org.wso2.am.microgw</groupId>
Do not specify group ID

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/pom.xml
> +    <artifactId>org.wso2.am.microgw.jwt-generator</artifactId>
Use the project group ID "org.wso2.performance.apim" as a prefix

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/pom.xml
> +        <dependency>
Use dependency management in parent pom and use properties for version.

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/pom.xml
> +        <main.class>org.wso2.am.microgw.jwt.JWTGenerator</main.class>
This is not required.

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/pom.xml
> +</project>
Add new line at the end of file.

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/src/main/java/org/wso2/am/microgw/jwt/JWTGenerator.java
> + * Base test class for CLI based tests
Is this correct?

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/src/main/java/org/wso2/am/microgw/jwt/JWTGenerator.java
> +import org.apache.commons.logging.Log;
Use slf4j

2019-01-18 09:37 UTC, chrishantha commented on components/jwtgenerator/src/main/java/org/wso2/am/microgw/jwt/JWTGenerator.java
> +        apiName = args[i++];
Use jcommander. For example, see https://github.com/wso2/performance-common/blob/4430a2808d342e7995b9c0e9dedfd17a2d60a7d5/components/netty-http-echo-service/src/main/java/org/wso2/performance/common/netty/echo/EchoHttpServer.java#L48-L49

2019-01-18 09:37 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/create-apis.sh
> +#!/bin/bash
Why did you create this file?

2019-01-18 09:37 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/create-micro-gw.sh
> +#!/usr/bin/expect
Add license header

2019-01-18 09:37 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/micro-gw-start.sh
> +if [ -e "/home/ubuntu/micro-gw-${label}/bin/gateway.pid" ]; then
Shouldn't we use a loop here?

2019-01-18 09:37 UTC, chrishantha commented on distribution/scripts/cloudformation/templates/apim_perf_test_cfn.yaml
> +#{
Why did you change this?

2019-01-18 09:37 UTC, chrishantha commented on pom.xml
> +            <dependency>
Why did you add this?

2019-01-18 10:10 UTC, tharikaGitHub commented on distribution/scripts/apim/micro-gw/create-apis.sh
> +#!/bin/bash
This file is different from apim/create-apis.sh. This does not create a mediation API. Will remove the sections not required for Microgateway testing.

2019-01-21 04:32 UTC, chrishantha requested changes

2019-01-21 04:32 UTC, chrishantha commented on distribution/bin.xml
> +        <file>
Use dependencySet. Look at performance-common. https://github.com/wso2/performance-common/blob/master/distribution/bin.xml#L32-L57

2019-01-21 04:57 UTC, chrishantha requested changes

2019-01-21 04:57 UTC, chrishantha commented on distribution/pom.xml
> +            <version>1.0.0</version>
Do not use version here.

2019-01-22 05:00 UTC, chrishantha requested changes

2019-01-22 05:00 UTC, chrishantha commented on distribution/pom.xml
> +            <version>${jwt.generator.version}</version>
Version shouldn't be here.

2019-01-22 05:00 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/generate-jwt-tokens.sh
> +	JWT_TOKEN=$(java -jar /home/ubuntu/jwt-generator/jwt-generator-1.0.0.jar --api-name "echo" --context "/echo" --version "1.0.0" --app-name "DefaultApplication" --app-tier "Unlimited" --subs-tier "Unl
Do not hard code path and version here.

2019-01-22 05:00 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/micro-gw-start.sh
> +label="echo-mgw"
This should be an option.

2019-01-22 05:00 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/micro-gw-start.sh
> +bash gateway > /dev/null &
This is not recommended. Execute as ./gateway

2019-01-22 05:00 UTC, chrishantha commented on pom.xml
> +        <jwt.generator.version>1.0.0</jwt.generator.version>
Remove jwt.generator.version. We don't need a specific version for jwt-generator

2019-01-22 05:00 UTC, chrishantha commented on distribution/scripts/cloudformation/run-micro-gw-performance-tests.sh
> +export aws_cloudformation_template_filename="apim_micro_gw_perf_test_cfn.yaml"
also export run_performance_tests_script_name="run-micro-gw-performance-tests.sh"

2019-01-22 05:00 UTC, chrishantha commented on components/jwt-generator/src/main/java/org/wso2/am/microgw/jwt/JWTGenerator.java
> +    @Parameter(names = "--api-name", description = "API Name") private String apiName;
Did you format code?

2019-01-22 05:00 UTC, chrishantha commented on distribution/scripts/apim/micro-gw/generate-jwt-tokens.sh
> +	JWT_TOKEN=$(java -jar /home/ubuntu/jwt-generator/jwt-generator-1.0.0.jar --api-name "echo" --context "/echo" --version "1.0.0" --app-name "DefaultApplication" --app-tier "Unlimited" --subs-tier "Unl
https://github.com/chrishantha/performance-common/blob/master/distribution/scripts/jtl-splitter/jtl-splitter.sh#L58

2019-01-22 08:24 UTC, tharikaGitHub commented on distribution/scripts/apim/micro-gw/micro-gw-start.sh
> +bash gateway > /dev/null &
Kept as bash gateway due to a limitation in the script.

2019-01-22 09:51 UTC, chrishantha requested changes

2019-01-22 09:51 UTC, chrishantha commented on pom.xml
> +        <slf4j.version.range>[1.7.0,1.8.0)</slf4j.version.range>
This is not required.

2019-01-22 09:51 UTC, chrishantha commented on pom.xml
> +        <org.json.version>20180130</org.json.version>
There is a newer version: https://search.maven.org/artifact/org.json/json/20180813/bundle

2019-01-22 09:51 UTC, chrishantha commented on distribution/scripts/cloudformation/run-micro-gw-performance-tests.sh
> +            echo "Please provide WSO2 API Microgateway distribution."
Format code: Use VSCode

2019-01-22 09:58 UTC, chrishantha approved these changes

2019-01-22 10:00 UTC, merged